---
- name: Download Cilium CLI
  shell: |
    curl -L --fail --remote-name-all https://github.com/cilium/cilium-cli/releases/latest/download/cilium-linux-amd64.tar.gz
    sudo tar xzvfC cilium-linux-amd64.tar.gz /usr/local/bin
    rm cilium-linux-amd64.tar.gz
  args:
    creates: /usr/local/bin/cilium
  when: inventory_hostname in groups['control_plane']

- name: Install Cilium using Cilium CLI
  shell: |
    cilium install --version {{ cilium_version }}
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  when: inventory_hostname in groups['control_plane']

- name: Wait for Cilium to be ready
  shell: cilium status --wait
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  when: inventory_hostname in groups['control_plane']
  register: cilium_ready
  retries: 5
  delay: 30
  until: cilium_ready.rc == 0

- name: Verify Cilium connectivity
  shell: cilium connectivity test
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  register: cilium_connectivity
  when: inventory_hostname in groups['control_plane']
  ignore_errors: yes

- name: Show Cilium status
  shell: cilium status
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  register: cilium_status_output
  when: inventory_hostname in groups['control_plane']

- name: Display Cilium status
  debug:
    var: cilium_status_output.stdout_lines
  when: inventory_hostname in groups['control_plane'] and cilium_status_output is defined
