---
- name: Get ArgoCD install manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: /tmp/argocd-install.yaml
    mode: '0644'
    owner: root
    group: root
- name: Create argocd namespace
  ansible.builtin.shell: |
    kubectl create namespace argocd
  register: argocd_namespace
  until: argocd_namespace.rc == 0
  retries: 2
  delay: 10
- name: Apply ArgoCD install manifest
  ansible.builtin.shell: |
    kubectl apply -f /tmp/argocd-install.yaml -n argocd
  register: argocd_install
  until: argocd_install.rc == 0
  retries: 2
  delay: 10
- name: Wait for ArgoCD pods to be ready
  ansible.builtin.shell: |
    kubectl wait --for=condition=Ready pods --all -n argocd --timeout=300s
  register: argocd_wait
  until: argocd_wait.rc == 0
  retries: 5
  delay: 10
