---
# Combined tasks for ArgoCD, Ingress, and Kubernetes Dashboard installation

# Setup kubectl config for root
- name: Ensure .kube directory exists for root
  file:
    path: /root/.kube
    state: directory
    owner: root
    group: root
    mode: '0700'

- name: Copy Kubernetes config for root
  copy:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    owner: root
    group: root
    mode: '0600'
    remote_src: yes

# ArgoCD Installation
- name: Get ArgoCD install manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: /tmp/argocd-install.yaml
    mode: '0644'
    owner: root
    group: root

- name: Check if argocd namespace exists
  shell: kubectl get namespace argocd
  register: argocd_ns_check
  ignore_errors: yes

- name: Create argocd namespace
  shell: kubectl create namespace argocd
  when: argocd_ns_check.rc != 0

- name: Apply ArgoCD install manifest
  ansible.builtin.shell: |
    kubectl apply -f /tmp/argocd-install.yaml -n argocd
  register: argocd_install
  until: argocd_install.rc == 0
  retries: 5
  delay: 10

- name: Wait for ArgoCD pods to be ready
  ansible.builtin.shell: |
    kubectl wait --for=condition=Ready pods --all -n argocd --timeout=300s
  register: argocd_wait
  until: argocd_wait.rc == 0
  retries: 5
  delay: 10

# Helm Installation
- name: Install Helm
  shell: |
    curl -fsSL https://get.helm.sh/helm-v3.14.0-linux-amd64.tar.gz -o /tmp/helm.tar.gz
    tar -zxvf /tmp/helm.tar.gz -C /tmp
    mv /tmp/linux-amd64/helm /usr/local/bin/helm
    chmod +x /usr/local/bin/helm
  args:
    creates: /usr/local/bin/helm

# Ingress Installation
- name: Add ingress-nginx Helm repo
  shell: |
    helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    helm repo update
  register: ingress_repo
  until: ingress_repo.rc == 0
  retries: 3
  delay: 5

- name: Install NGINX Ingress Controller
  shell: |
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx --create-namespace --namespace ingress-nginx
  register: ingress_install
  until: ingress_install.rc == 0
  retries: 3
  delay: 10

- name: Wait for Ingress Controller pods to be ready
  shell: |
    kubectl wait --for=condition=Ready pods --all -n ingress-nginx --timeout=300s
  register: ingress_wait
  until: ingress_wait.rc == 0
  retries: 5
  delay: 10

 ## Kubernetes Dashboard Installation
- name: Add kubernetes-dashboard Helm repo
  shell: |
    helm repo add kubernetes-dashboard https://kubernetes.github.io/dashboard/
    helm repo update
  register: helm_repo
  until: helm_repo.rc == 0
  retries: 3
  delay: 5

- name: Install Kubernetes Dashboard
  shell: |
    helm upgrade --install kubernetes-dashboard kubernetes-dashboard/kubernetes-dashboard --create-namespace --namespace kubernetes-dashboard
  register: dashboard_install
  until: dashboard_install.rc == 0
  retries: 3
  delay: 10

- name: Wait for Dashboard pods to be ready
  shell: |
    kubectl wait --for=condition=Ready pods --all -n kubernetes-dashboard --timeout=300s
  register: dashboard_wait
  until: dashboard_wait.rc == 0
  retries: 5
  delay: 10
